
# Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
# Click nbfs://nbhost/SystemFileSystem/Templates/Other/properties.properties to edit this template


# Credenciales de Twilio
twilio.account.sid=YOUR_ACCOUNT_SID
twilio.auth.token=YOUR_ACCOUNT_SID

# N\u00famero de WhatsApp Sandbox
twilio.whatsapp.number=+14155238886